name: Sync Fork

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch:  # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # 获取所有的历史记录

      - name: Set up Git
        run: |
          git config --local user.email "you@example.com"
          git config --local user.name "Your Name"

      - name: Fetch upstream
        run: |
          git remote add upstream https://github.com/unilei/aipan-netdisk-search.git
          git fetch upstream

      - name: Merge changes
        run: |
          git checkout main
          git merge upstream/main  # 根据你的主分支调整

      - name: Push changes
        run: |
          git push origin main  # 根据你的主分支调整
